import Head from "next/head";
import Header from "./header";

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>
          {title ? `${title}` : "E Commerce"} by Asadullah Hil Galib
        </title>
        <meta
          name="description"
          content="E Commerce - Generated by create next app - Developer by Asadullah Hil Galib"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex justify-between flex-col">
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer>Footer</footer>
      </div>
    </>
  );
}
