import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>E Commerce by Asadullah Hil Galib</title>
        <meta
          name="description"
          content="E Commerce - Generated by create next app - Developer by Asadullah Hil Galib"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Welcome to another project</main>
    </>
  );
}
